services:
  # Frontend
  - type: web
    name: prescripto-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: NODE_ENV
        value: production

  # Admin Dashboard
  - type: web
    name: prescripto-admin
    env: node
    buildCommand: cd admin && npm install && npm run build
    startCommand: cd admin && npm start
    envVars:
      - key: NODE_ENV
        value: production

  # Backend API
  - type: web
    name: prescripto-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production 